export const fieldNames = {
  title: 'Title',
  description: 'Description',
  deadline: 'Deadline',
  department: 'Department',
  prototype_url: 'Prototype URL',
  assets_url: 'Assets URL',
  request_type: 'Request Type',
  access_url: 'Access URL',
  receiver: 'Receiver',
  parent: 'Parent Page',
  page_url: 'Page URL',
  access_details: 'Access Details',
  priority: 'Priority',
  flow: 'Flow',
  display_details: 'Display Details',
  preconditions: 'Preconditions',
  sketch: 'Sketch',
}
